export interface Project {
  id: string
  name: string
  nameKey: string
  shortLabel: string
  shortLabelKey: string
  tagline: string
  taglineKey: string
  description: string
  descriptionKey: string
  techStack: string[]
  status: 'active' | 'stable' | 'research' | 'legacy' | 'preview'
  repo?: string
  color: string
  icon: string
}

export const projects: Project[] = [
  {
    id: 'entelecheia',
    name: 'Entelecheia',
    nameKey: 'entelecheia.name',
    shortLabel: 'Multi-Agent Platform',
    shortLabelKey: 'entelecheia.shortLabel',
    tagline: 'Multi-Agent Platform for Industrial AI Control',
    taglineKey: 'entelecheia.tagline',
    description: 'An exec-only microkernel multi-agent platform built for safety-critical industrial control. The LLM sees only a handful of primitives — all real work runs inside the IEPL TypeScript pipeline, dispatching to a large MCP tool surface across many agents, with cross-vendor protocol support (Modbus, S7comm, OPC UA) and multi-layer safety gates.',
    descriptionKey: 'entelecheia.description',
    techStack: ['Rust', 'TypeScript', 'MCP', 'Modbus', 'OPC UA'],
    status: 'preview',
    repo: 'celestia-island/entelecheia',
    color: '#8b5cf6',
    icon: 'i-lucide-bot',
  },
  {
    id: 'shittim-chest',
    name: 'Shittim Chest',
    nameKey: 'shittim.name',
    shortLabel: 'Agent Chat & Control Panel',
    shortLabelKey: 'shittim.shortLabel',
    tagline: 'Chat With Your AI Agents',
    taglineKey: 'shittim.tagline',
    description: 'The interactive face of Entelecheia — a streaming chat interface to converse with AI agents, a control panel to configure systems and manage permissions, plus desktop and mobile apps. Everything the user sees and touches.',
    descriptionKey: 'shittim.description',
    techStack: ['Vue 3', 'TypeScript', 'Rust', 'CSS'],
    status: 'preview',
    repo: 'celestia-island/shittim-chest',
    color: '#06b6d4',
    icon: 'i-lucide-message-square',
  },
  {
    id: 'evernight',
    name: 'Evernight',
    nameKey: 'evernight.name',
    shortLabel: 'Protocol Broker & Remote Control',
    shortLabelKey: 'evernight.shortLabel',
    tagline: 'Cross-platform remote control & industrial-protocol broker',
    taglineKey: 'evernight.tagline',
    description: 'Screen streaming, SSH/VNC/RDP, hardware telemetry, and industrial protocols — Modbus, S7comm, OPC UA, CAN, EtherCAT. The layer that connects cloud AI agents to physical devices and orchestrates containers and VMs at the edge.',
    descriptionKey: 'evernight.description',
    techStack: ['Rust', 'Modbus', 'S7comm', 'OPC UA'],
    status: 'preview',
    repo: 'celestia-island/evernight',
    color: '#4f46e5',
    icon: 'i-lucide-network',
  },
  {
    id: 'aris',
    name: 'ARIS',
    nameKey: 'aris.name',
    shortLabel: 'Embedded IoT Gateway OS',
    shortLabelKey: 'aris.shortLabel',
    tagline: 'Embedded OS for industrial IoT gateways',
    taglineKey: 'aris.tagline',
    description: 'The embedded OS and firmware for the Entelecheia industrial IoT gateway. It runs evernight on ARM/RISC-V edge devices, bridging the protocol broker to physical hardware — PLCs, sensors, valves — through a minimal, secure kernel layer.',
    descriptionKey: 'aris.description',
    techStack: ['Rust', 'ARM64', 'RISC-V', 'no_std'],
    status: 'preview',
    color: '#eab308',
    icon: 'i-lucide-circuit-board',
  },
  {
    id: 'kei',
    name: 'KEI',
    nameKey: 'kei.name',
    shortLabel: 'ARM64 Industrial Kernel',
    shortLabelKey: 'kei.shortLabel',
    tagline: 'Asterinas ARM64 fork for industrial IoT gateways',
    taglineKey: 'kei.tagline',
    description: 'An independent fork of asterinas with ARM64 support and board support packages for industrial IoT gateways. It provides the kei-kernel.bin consumed by aris — absorbing upstream changes on its own schedule rather than tracking them as a branch.',
    descriptionKey: 'kei.description',
    techStack: ['Rust', 'ARM64', 'OS Kernel', 'BSP'],
    status: 'research',
    color: '#3b82f6',
    icon: 'i-lucide-binary',
  },
  {
    id: 'tairitsu',
    name: 'Tairitsu',
    nameKey: 'tairitsu.name',
    shortLabel: 'WASI Full-Stack Framework',
    shortLabelKey: 'tairitsu.shortLabel',
    tagline: 'Full-Stack, WASI-Native',
    taglineKey: 'tairitsu.tagline',
    description: 'Build complete web applications that target WASI — a single, portable runtime for both frontend and backend. Write your UI and server logic in Rust, compile to WASI components, and deploy to browser, server, or edge. One runtime, one language, one codebase.',
    descriptionKey: 'tairitsu.description',
    techStack: ['Rust', 'WASI', 'TypeScript', 'CSS', 'WIT'],
    status: 'active',
    repo: 'celestia-island/tairitsu',
    color: '#ec4899',
    icon: 'i-lucide-boxes',
  },
  {
    id: 'hikari',
    name: 'Hikari',
    nameKey: 'hikari.name',
    shortLabel: 'WASI UI Component Library',
    shortLabelKey: 'hikari.shortLabel',
    tagline: 'WASI-Native UI Framework',
    taglineKey: 'hikari.tagline',
    description: 'A UI component library purpose-built for WASI. Polished, ready-made components that run on the same WASI runtime as your backend — no wasm-bindgen, no JavaScript glue. Build interfaces once, render them anywhere.',
    descriptionKey: 'hikari.description',
    techStack: ['Rust', 'WASI', 'SCSS', 'CSS', 'WIT'],
    status: 'active',
    repo: 'celestia-island/hikari',
    color: '#f59e0b',
    icon: 'i-lucide-palette',
  },
  {
    id: 'lagrange',
    name: 'Lagrange',
    nameKey: 'lagrange.name',
    shortLabel: 'WASI Markdown Site Generator',
    shortLabelKey: 'lagrange.shortLabel',
    tagline: 'WASI-rendered multilingual Markdown static site',
    taglineKey: 'lagrange.tagline',
    description: 'Turn a folder of Markdown into a static, multilingual documentation site — WASI-rendered, with a built-in language switcher and root redirect. No JavaScript framework, no mdBook, no Node toolchain. Lagrange builds its own documentation.',
    descriptionKey: 'lagrange.description',
    techStack: ['Rust', 'WASI', 'Markdown', 'HTML'],
    status: 'active',
    repo: 'celestia-island/lagrange',
    color: '#10b981',
    icon: 'i-lucide-globe',
  },
  {
    id: 'aoba',
    name: 'Aoba',
    nameKey: 'aoba.name',
    shortLabel: 'Modbus Debug Tool',
    shortLabelKey: 'aoba.shortLabel',
    tagline: 'Industrial Protocol Debugging, Made Effortless',
    taglineKey: 'aoba.tagline',
    description: 'Inspect, test, and simulate Modbus industrial devices right from your terminal. Connect to real hardware, spin up virtual devices for testing, and bridge data between protocols — an indispensable companion for automation engineers on the factory floor and in CI pipelines.',
    descriptionKey: 'aoba.description',
    techStack: ['Rust', 'Shell', 'SCSS'],
    status: 'stable',
    repo: 'celestia-island/aoba',
    color: '#22c55e',
    icon: 'i-lucide-terminal',
  },
  {
    id: 'kirino',
    name: 'Kirino',
    nameKey: 'kirino.name',
    shortLabel: 'Auth & RBAC Framework',
    shortLabelKey: 'kirino.shortLabel',
    tagline: 'Zero-trust auth & RBAC, with trust scoring',
    taglineKey: 'kirino.tagline',
    description: 'A fully generic, trait-based authentication and authorization framework for Rust. Complete RBAC (RBAC0/1/2) implementing ANSI INCITS 359-2004, plus a dynamic authorization layer with trust scoring, anomaly detection, and DO-178C-inspired autonomy levels (L0–L4).',
    descriptionKey: 'kirino.description',
    techStack: ['Rust', 'RBAC', 'SQL'],
    status: 'stable',
    repo: 'celestia-island/kirino',
    color: '#ef4444',
    icon: 'i-lucide-shield-check',
  },
  {
    id: 'ratatui-markdown',
    name: 'Ratatui Markdown',
    nameKey: 'ratatui-markdown.name',
    shortLabel: 'TUI Markdown',
    shortLabelKey: 'ratatui-markdown.shortLabel',
    tagline: 'Rich markdown and diagrams for terminal apps',
    taglineKey: 'ratatui-markdown.tagline',
    description: 'Markdown rendering, syntax highlighting, Mermaid diagrams, collapsible JSON/TOML trees, and a hybrid scroll system — all built on ratatui. Feature-gated for selective inclusion in any TUI application.',
    descriptionKey: 'ratatui-markdown.description',
    techStack: ['Rust', 'ratatui', 'Tree-sitter'],
    status: 'active',
    repo: 'celestia-island/ratatui-markdown',
    color: '#0ea5e9',
    icon: 'i-lucide-scroll-text',
  },
  {
    id: 'yuuka',
    name: 'Yuuka',
    nameKey: 'yuuka.name',
    shortLabel: 'Nested Type Generator',
    shortLabelKey: 'yuuka.shortLabel',
    tagline: 'Define deeply nested types in one sweep',
    taglineKey: 'yuuka.tagline',
    description: 'A proc-macro library that generates complex, deeply nested structs and enums from a compact DSL. Inline types are automatically flattened, derived, and wired up with serde — write one macro invocation, get an entire type hierarchy.',
    descriptionKey: 'yuuka.description',
    techStack: ['Rust', 'proc-macro', 'Serde'],
    status: 'active',
    repo: 'celestia-island/yuuka',
    color: '#a78bfa',
    icon: 'i-lucide-layers',
  },
  {
    id: 'ichika',
    name: 'Ichika',
    nameKey: 'ichika.name',
    shortLabel: 'Pipeline Threading Library',
    shortLabelKey: 'ichika.shortLabel',
    tagline: 'Declarative thread-pool pipelines via macro',
    taglineKey: 'ichika.tagline',
    description: 'Declaratively define multi-stage processing pipelines from closures. The pipe! macro generates all thread wiring and channel plumbing automatically — supporting mixed sync/async steps, branching, retry policies, and graceful shutdown.',
    descriptionKey: 'ichika.description',
    techStack: ['Rust', 'proc-macro', 'Flume', 'Tokio'],
    status: 'active',
    repo: 'celestia-island/ichika',
    color: '#14b8a6',
    icon: 'i-lucide-workflow',
  },
  {
    id: 'hifumi',
    name: 'Hifumi',
    nameKey: 'hifumi.name',
    shortLabel: 'Data Migration Library',
    shortLabelKey: 'hifumi.shortLabel',
    tagline: 'Version your structs, migrate your data',
    taglineKey: 'hifumi.tagline',
    description: 'A serialization library for migrating data between struct versions. Annotate your types with version attributes and migration rules — Hifumi auto-generates all older-version structs and From impls, plus a CLI to diff structs across git history.',
    descriptionKey: 'hifumi.description',
    techStack: ['Rust', 'proc-macro', 'Serde', 'Git'],
    status: 'active',
    repo: 'celestia-island/hifumi',
    color: '#d946ef',
    icon: 'i-lucide-git-compare',
  },
  {
    id: 'noa',
    name: 'Noa',
    nameKey: 'noa.name',
    shortLabel: 'Distributed Version Control',
    shortLabelKey: 'noa.shortLabel',
    tagline: 'AI-native distributed version control',
    taglineKey: 'noa.tagline',
    description: 'Per-agent workspace isolation, append-only JSONL logs, snapshot-based history, and full git protocol compatibility — version control designed from the ground up for AI agents that branch constantly and rewrite history.',
    descriptionKey: 'noa.description',
    techStack: ['Rust', 'Git', 'JSONL', 'Serde'],
    status: 'preview',
    repo: 'celestia-island/noa',
    color: '#fb923c',
    icon: 'i-lucide-git-branch',
  },
  {
    id: 'kou',
    name: 'kou',
    nameKey: 'kou.name',
    shortLabel: 'Virtual Terminal Engine',
    shortLabelKey: 'kou.shortLabel',
    tagline: 'Standalone virtual-terminal engine',
    taglineKey: 'kou.tagline',
    description: 'PTY management, a VT100/ANSI screen emulator, and glyph-rendering screen output in one library and CLI. The vtty core extracted from the tairitsu packager — a real CSI/SGR-honouring screen, not a bare PTY wrapper.',
    descriptionKey: 'kou.description',
    techStack: ['Rust', 'VT100', 'PTY', 'vte'],
    status: 'active',
    color: '#65a30d',
    icon: 'i-lucide-square-terminal',
  },
  {
    id: 'malkuth',
    name: 'Malkuth',
    nameKey: 'malkuth.name',
    shortLabel: 'Service Supervision Toolkit',
    shortLabelKey: 'malkuth.shortLabel',
    tagline: 'Composable service-supervision toolkit for Rust',
    taglineKey: 'malkuth.tagline',
    description: 'Graceful shutdown, health probes, coordination locks, and rolling updates for long-running Rust programs. Pluggable transport (JSON-RPC over TCP/WebSocket/IPC), supervised workers, and a watchdog CLI that wraps any program with file watching and a sticky reverse proxy.',
    descriptionKey: 'malkuth.description',
    techStack: ['Rust', 'JSON-RPC', 'IPC', 'Tokio'],
    status: 'active',
    repo: 'celestia-island/malkuth',
    color: '#9333ea',
    icon: 'i-lucide-activity',
  },
  {
    id: 'seia',
    name: 'seia',
    nameKey: 'seia.name',
    shortLabel: 'Multi-Engine Web Search',
    shortLabelKey: 'seia.shortLabel',
    tagline: 'Multi-engine web search library and CLI',
    taglineKey: 'seia.tagline',
    description: 'A unified interface to query diverse search backends. Engines that need no authentication work out of the box with zero configuration — a library and CLI for routing one query across many providers and merging the results.',
    descriptionKey: 'seia.description',
    techStack: ['Rust', 'Search', 'CLI', 'Serde'],
    status: 'active',
    repo: 'celestia-island/seia',
    color: '#1d4ed8',
    icon: 'i-lucide-search',
  },
  {
    id: 'shirabe',
    name: 'shirabe',
    nameKey: 'shirabe.name',
    shortLabel: 'Headless Browser Automation',
    shortLabelKey: 'shirabe.shortLabel',
    tagline: 'Rust-native headless browser automation',
    taglineKey: 'shirabe.tagline',
    description: 'A lightweight, Rust-native browser automation library and debug server. It drives any CDP-speaking browser — Chrome, Chromium, Edge — through one hand-rolled engine, fetching and pinning a Chrome for Testing build so you never install a browser by hand.',
    descriptionKey: 'shirabe.description',
    techStack: ['Rust', 'CDP', 'Chrome', 'HTTP'],
    status: 'active',
    color: '#db2777',
    icon: 'i-lucide-app-window',
  },
]
