export interface Project {
  id: string
  name: string
  nameKey: string
  shortLabel: string
  shortLabelKey: string
  tagline: string
  taglineKey: string
  description: string
  descriptionKey: string
  techStack: string[]
  status: 'active' | 'stable' | 'research' | 'legacy' | 'preview'
  repo?: string
  color: string
  icon: string
}

export const projects: Project[] = [
  {
    id: 'entelecheia',
    name: 'Entelecheia',
    nameKey: 'entelecheia.name',
    shortLabel: 'Multi-Agent Platform',
    shortLabelKey: 'entelecheia.shortLabel',
    tagline: 'Industrial AI control platform',
    taglineKey: 'entelecheia.tagline',
    description: 'An exec-only multi-agent platform for safety-critical industrial control — the LLM only orchestrates, all real work runs through typed pipelines and MCP tools.',
    descriptionKey: 'entelecheia.description',
    techStack: ['Rust', 'TypeScript', 'MCP', 'Modbus', 'OPC UA'],
    status: 'preview',
    color: '#8b5cf6',
    icon: 'i-lucide-bot',
  },
  {
    id: 'shittim-chest',
    name: 'Shittim Chest',
    nameKey: 'shittim.name',
    shortLabel: 'Agent Chat & Control Panel',
    shortLabelKey: 'shittim.shortLabel',
    tagline: 'Chat With Your AI Agents',
    taglineKey: 'shittim.tagline',
    description: 'The interactive face of Entelecheia — a streaming chat interface to converse with AI agents, a control panel to configure systems and manage permissions, plus desktop and mobile apps. Everything the user sees and touches.',
    descriptionKey: 'shittim.description',
    techStack: ['Vue 3', 'TypeScript', 'Rust', 'CSS'],
    status: 'preview',
    color: '#06b6d4',
    icon: 'i-lucide-message-square',
  },
  {
    id: 'evernight',
    name: 'Evernight',
    nameKey: 'evernight.name',
    shortLabel: 'Protocol Broker & Remote Control',
    shortLabelKey: 'evernight.shortLabel',
    tagline: 'Industrial protocols, bridged to the cloud',
    taglineKey: 'evernight.tagline',
    description: 'Screen streaming, SSH/VNC/RDP, and industrial protocols (Modbus, OPC UA, CAN) — the bridge between cloud agents and physical devices.',
    descriptionKey: 'evernight.description',
    techStack: ['Rust', 'Modbus', 'S7comm', 'OPC UA'],
    status: 'preview',
    color: '#4f46e5',
    icon: 'i-lucide-network',
  },
  {
    id: 'aris',
    name: 'ARIS',
    nameKey: 'aris.name',
    shortLabel: 'Browser Engine',
    shortLabelKey: 'aris.shortLabel',
    tagline: 'Pure-Rust browser engine on servo',
    taglineKey: 'aris.tagline',
    description: 'A browser engine derived from servo — embed it as a Rust library or run it standalone, with C++ components replaced by pure Rust.',
    descriptionKey: 'aris.description',
    techStack: ['Rust', 'servo', 'Boa', 'Vello', 'Wasmtime'],
    status: 'active',
    repo: 'celestia-island/aris',
    color: '#eab308',
    icon: 'i-lucide-monitor',
  },
  {
    id: 'kei',
    name: 'KEI',
    nameKey: 'kei.name',
    shortLabel: 'IoT OS Kernel',
    shortLabelKey: 'kei.shortLabel',
    tagline: 'Rust OS kernel for edge devices',
    taglineKey: 'kei.tagline',
    description: 'A Rust OS kernel for ARM64 and RISC-V edge devices, derived from Asterinas, with industrial drivers and a no_std sensor library.',
    descriptionKey: 'kei.description',
    techStack: ['Rust', 'Asterinas', 'ARM64', 'RTOS'],
    status: 'active',
    repo: 'celestia-island/kei',
    color: '#3b82f6',
    icon: 'i-lucide-binary',
  },
  {
    id: 'tairitsu',
    name: 'Tairitsu',
    nameKey: 'tairitsu.name',
    shortLabel: 'WASI Full-Stack Framework',
    shortLabelKey: 'tairitsu.shortLabel',
    tagline: 'One runtime, frontend to backend',
    taglineKey: 'tairitsu.tagline',
    description: 'Build full web apps on a single WASI runtime — write UI and server in Rust, compile to WASI components, deploy anywhere.',
    descriptionKey: 'tairitsu.description',
    techStack: ['Rust', 'WASI', 'TypeScript', 'CSS', 'WIT'],
    status: 'active',
    repo: 'celestia-island/tairitsu',
    color: '#ec4899',
    icon: 'i-lucide-boxes',
  },
  {
    id: 'hikari',
    name: 'Hikari',
    nameKey: 'hikari.name',
    shortLabel: 'WASI UI Components',
    shortLabelKey: 'hikari.shortLabel',
    tagline: 'UI components for WASI',
    taglineKey: 'hikari.tagline',
    description: 'A polished component library that runs on the same WASI runtime as your backend — no wasm-bindgen, no JS glue.',
    descriptionKey: 'hikari.description',
    techStack: ['Rust', 'WASI', 'SCSS', 'CSS', 'WIT'],
    status: 'active',
    repo: 'celestia-island/hikari',
    color: '#f59e0b',
    icon: 'i-lucide-palette',
  },
  {
    id: 'lagrange',
    name: 'Lagrange',
    nameKey: 'lagrange.name',
    shortLabel: 'Markdown Site Generator',
    shortLabelKey: 'lagrange.shortLabel',
    tagline: 'Multilingual Markdown static site',
    taglineKey: 'lagrange.tagline',
    description: 'Turn a folder of Markdown into a static, multilingual docs site — no JS framework, no Node toolchain.',
    descriptionKey: 'lagrange.description',
    techStack: ['Rust', 'Markdown', 'HTML'],
    status: 'active',
    repo: 'celestia-island/lagrange',
    color: '#10b981',
    icon: 'i-lucide-globe',
  },
  {
    id: 'aoba',
    name: 'Aoba',
    nameKey: 'aoba.name',
    shortLabel: 'Modbus Debug Tool',
    shortLabelKey: 'aoba.shortLabel',
    tagline: 'Modbus debugging, in your terminal',
    taglineKey: 'aoba.tagline',
    description: 'Inspect, test, and simulate Modbus devices from the terminal — connect to real hardware or spin up virtual ones.',
    descriptionKey: 'aoba.description',
    techStack: ['Rust', 'Shell', 'SCSS'],
    status: 'stable',
    repo: 'celestia-island/aoba',
    color: '#22c55e',
    icon: 'i-lucide-terminal',
  },
  {
    id: 'kirino',
    name: 'Kirino',
    nameKey: 'kirino.name',
    shortLabel: 'Auth & RBAC Framework',
    shortLabelKey: 'kirino.shortLabel',
    tagline: 'Trait-based auth, RBAC, and trust scoring',
    taglineKey: 'kirino.tagline',
    description: 'A generic Rust auth and authorization framework with full RBAC and a dynamic trust-scoring layer.',
    descriptionKey: 'kirino.description',
    techStack: ['Rust', 'RBAC', 'SQL'],
    status: 'stable',
    repo: 'celestia-island/kirino',
    color: '#ef4444',
    icon: 'i-lucide-shield-check',
  },
  {
    id: 'ratatui-markdown',
    name: 'Ratatui Markdown',
    nameKey: 'ratatui-markdown.name',
    shortLabel: 'TUI Markdown',
    shortLabelKey: 'ratatui-markdown.shortLabel',
    tagline: 'Markdown and diagrams for TUI apps',
    taglineKey: 'ratatui-markdown.tagline',
    description: 'Markdown rendering, syntax highlighting, Mermaid diagrams, and collapsible trees — all on ratatui.',
    descriptionKey: 'ratatui-markdown.description',
    techStack: ['Rust', 'ratatui', 'Tree-sitter'],
    status: 'active',
    repo: 'celestia-island/ratatui-markdown',
    color: '#0ea5e9',
    icon: 'i-lucide-scroll-text',
  },
  {
    id: 'yuuka',
    name: 'Yuuka',
    nameKey: 'yuuka.name',
    shortLabel: 'Nested Type Generator',
    shortLabelKey: 'yuuka.shortLabel',
    tagline: 'Nested types from one macro',
    taglineKey: 'yuuka.tagline',
    description: 'A proc-macro that generates deeply nested structs and enums from a compact DSL, with serde wiring.',
    descriptionKey: 'yuuka.description',
    techStack: ['Rust', 'proc-macro', 'Serde'],
    status: 'active',
    repo: 'celestia-island/yuuka',
    color: '#a78bfa',
    icon: 'i-lucide-layers',
  },
  {
    id: 'ichika',
    name: 'Ichika',
    nameKey: 'ichika.name',
    shortLabel: 'Pipeline Threading Library',
    shortLabelKey: 'ichika.shortLabel',
    tagline: 'Declarative thread-pool pipelines',
    taglineKey: 'ichika.tagline',
    description: 'Define multi-stage processing pipelines from closures — the macro generates all threading and channels.',
    descriptionKey: 'ichika.description',
    techStack: ['Rust', 'proc-macro', 'Flume', 'Tokio'],
    status: 'active',
    repo: 'celestia-island/ichika',
    color: '#14b8a6',
    icon: 'i-lucide-workflow',
  },
  {
    id: 'hifumi',
    name: 'Hifumi',
    nameKey: 'hifumi.name',
    shortLabel: 'Data Migration Library',
    shortLabelKey: 'hifumi.shortLabel',
    tagline: 'Version your structs, migrate data',
    taglineKey: 'hifumi.tagline',
    description: 'A serialization library that generates older-version structs and migrations from version attributes.',
    descriptionKey: 'hifumi.description',
    techStack: ['Rust', 'proc-macro', 'Serde', 'Git'],
    status: 'active',
    repo: 'celestia-island/hifumi',
    color: '#d946ef',
    icon: 'i-lucide-git-compare',
  },
  {
    id: 'noa',
    name: 'Noa',
    nameKey: 'noa.name',
    shortLabel: 'Distributed Version Control',
    shortLabelKey: 'noa.shortLabel',
    tagline: 'Version control for AI agents',
    taglineKey: 'noa.tagline',
    description: 'Per-agent workspaces, append-only logs, and git protocol compatibility — designed for agents that branch and rewrite constantly.',
    descriptionKey: 'noa.description',
    techStack: ['Rust', 'Git', 'JSONL', 'Serde'],
    status: 'preview',
    repo: 'celestia-island/noa',
    color: '#fb923c',
    icon: 'i-lucide-git-branch',
  },
  {
    id: 'kou',
    name: 'Kou',
    nameKey: 'kou.name',
    shortLabel: 'Virtual Terminal Engine',
    shortLabelKey: 'kou.shortLabel',
    tagline: 'Standalone terminal engine',
    taglineKey: 'kou.tagline',
    description: 'PTY management and a VT100/ANSI screen emulator in one library and CLI.',
    descriptionKey: 'kou.description',
    techStack: ['Rust', 'VT100', 'PTY', 'vte'],
    status: 'active',
    repo: 'celestia-island/kou',
    color: '#65a30d',
    icon: 'i-lucide-square-terminal',
  },
  {
    id: 'malkuth',
    name: 'Malkuth',
    nameKey: 'malkuth.name',
    shortLabel: 'Service Supervision Toolkit',
    shortLabelKey: 'malkuth.shortLabel',
    tagline: 'Graceful shutdown and health probes',
    taglineKey: 'malkuth.tagline',
    description: 'Graceful shutdown, health probes, coordination locks, and rolling updates for long-running Rust services.',
    descriptionKey: 'malkuth.description',
    techStack: ['Rust', 'JSON-RPC', 'IPC', 'Tokio'],
    status: 'active',
    repo: 'celestia-island/malkuth',
    color: '#9333ea',
    icon: 'i-lucide-activity',
  },
  {
    id: 'seia',
    name: 'Seia',
    nameKey: 'seia.name',
    shortLabel: 'Multi-Engine Web Search',
    shortLabelKey: 'seia.shortLabel',
    tagline: 'One query, many search engines',
    taglineKey: 'seia.tagline',
    description: 'A unified library and CLI to route one query across many search backends and merge the results.',
    descriptionKey: 'seia.description',
    techStack: ['Rust', 'Search', 'CLI', 'Serde'],
    status: 'active',
    repo: 'celestia-island/seia',
    color: '#1d4ed8',
    icon: 'i-lucide-search',
  },
  {
    id: 'shirabe',
    name: 'Shirabe',
    nameKey: 'shirabe.name',
    shortLabel: 'Headless Browser Automation',
    shortLabelKey: 'shirabe.shortLabel',
    tagline: 'Rust-native browser automation',
    taglineKey: 'shirabe.tagline',
    description: 'Drive any CDP-speaking browser through one Rust engine — it even pins a Chrome build for you.',
    descriptionKey: 'shirabe.description',
    techStack: ['Rust', 'CDP', 'Chrome', 'HTTP'],
    status: 'active',
    repo: 'celestia-island/shirabe',
    color: '#db2777',
    icon: 'i-lucide-app-window',
  },
]
