export interface Project {
  id: string
  name: string
  nameKey: string
  shortLabel: string
  shortLabelKey: string
  tagline: string
  taglineKey: string
  description: string
  descriptionKey: string
  techStack: string[]
  status: 'active' | 'stable' | 'research' | 'legacy' | 'preview'
  repo?: string
  color: string
  icon: string
}

export const projects: Project[] = [
  {
    id: 'entelecheia',
    name: 'Entelecheia',
    nameKey: 'entelecheia.name',
    shortLabel: 'Multi-Agent Platform',
    shortLabelKey: 'entelecheia.shortLabel',
    tagline: 'Multi-Agent Collaboration Platform',
    taglineKey: 'entelecheia.tagline',
    description: 'A Rust-based multi-agent collaboration platform with an exec-only microkernel design. Agents interact through ES module imports in an IEPL TypeScript layer, keeping the LLM surface minimal and composable.',
    descriptionKey: 'entelecheia.description',
    techStack: ['Rust', 'TypeScript', 'Boa JS', 'SQL', 'MCP'],
    status: 'preview',
    color: '#8b5cf6',
    icon: 'i-lucide-bot',
  },
  {
    id: 'shittim-chest',
    name: 'Shittim Chest',
    nameKey: 'shittim.name',
    shortLabel: 'Agent Chat & Control Panel',
    shortLabelKey: 'shittim.shortLabel',
    tagline: 'Chat With Your AI Agents',
    taglineKey: 'shittim.tagline',
    description: 'The interactive face of Entelecheia — a streaming chat interface to converse with AI agents, a control panel to configure systems and manage permissions, plus desktop and mobile apps. Everything the user sees and touches.',
    descriptionKey: 'shittim.description',
    techStack: ['Vue 3', 'TypeScript', 'Rust', 'CSS'],
    status: 'preview',
    color: '#06b6d4',
    icon: 'i-lucide-message-square',
  },
  {
    id: 'tairitsu',
    name: 'Tairitsu',
    nameKey: 'tairitsu.name',
    shortLabel: 'WASI Full-Stack Framework',
    shortLabelKey: 'tairitsu.shortLabel',
    tagline: 'Full-Stack, WASI-Native',
    taglineKey: 'tairitsu.tagline',
    description: 'Build complete web applications that target WASI — a single, portable runtime for both frontend and backend. Write your UI and server logic in Rust, compile to WASI components, and deploy to browser, server, or edge. One runtime, one language, one codebase.',
    descriptionKey: 'tairitsu.description',
    techStack: ['Rust', 'WASI', 'TypeScript', 'CSS', 'WIT'],
    status: 'active',
    repo: 'celestia-island/tairitsu',
    color: '#ec4899',
    icon: 'i-lucide-boxes',
  },
  {
    id: 'hikari',
    name: 'Hikari',
    nameKey: 'hikari.name',
    shortLabel: 'WASI UI Component Library',
    shortLabelKey: 'hikari.shortLabel',
    tagline: 'WASI-Native UI Framework',
    taglineKey: 'hikari.tagline',
    description: 'A UI component library purpose-built for WASI. Polished, ready-made components that run on the same WASI runtime as your backend — no wasm-bindgen, no JavaScript glue. Build interfaces once, render them anywhere.',
    descriptionKey: 'hikari.description',
    techStack: ['Rust', 'WASI', 'SCSS', 'CSS', 'WIT'],
    status: 'active',
    repo: 'celestia-island/hikari',
    color: '#f59e0b',
    icon: 'i-lucide-palette',
  },
  {
    id: 'aoba',
    name: 'Aoba',
    nameKey: 'aoba.name',
    shortLabel: 'Modbus Debugging Tool',
    shortLabelKey: 'aoba.shortLabel',
    tagline: 'Industrial Protocol Debugging, Made Effortless',
    taglineKey: 'aoba.tagline',
    description: 'Inspect, test, and simulate Modbus industrial devices right from your terminal. Connect to real hardware, spin up virtual devices for testing, and bridge data between protocols — an indispensable companion for automation engineers on the factory floor and in CI pipelines.',
    descriptionKey: 'aoba.description',
    techStack: ['Rust', 'Shell', 'SCSS'],
    status: 'stable',
    repo: 'celestia-island/aoba',
    color: '#22c55e',
    icon: 'i-lucide-terminal',
  },
  {
    id: 'kirino',
    name: 'Kirino',
    nameKey: 'kirino.name',
    shortLabel: 'RBAC Library',
    shortLabelKey: 'kirino.shortLabel',
    tagline: 'Production-Grade RBAC, Constrained by Design',
    taglineKey: 'kirino.tagline',
    description: 'Customizable zero-trust authentication & RBAC framework in Rust. Supports ANSI INCITS 359-2004 role hierarchies, separation of duties, and temporal constraints.',
    descriptionKey: 'kirino.description',
    techStack: ['Rust', 'SQL'],
    status: 'stable',
    repo: 'celestia-island/kirino',
    color: '#ef4444',
    icon: 'i-lucide-shield-check',
  },
  {
    id: 'ratatui-markdown',
    name: 'Ratatui Markdown',
    nameKey: 'ratatui-markdown.name',
    shortLabel: 'TUI Markdown Renderer',
    shortLabelKey: 'ratatui-markdown.shortLabel',
    tagline: 'Rich markdown and diagrams for terminal apps',
    taglineKey: 'ratatui-markdown.tagline',
    description: 'Markdown rendering, syntax highlighting, Mermaid diagrams, collapsible JSON/TOML trees, and a hybrid scroll system — all built on ratatui. Feature-gated for selective inclusion in any TUI application.',
    descriptionKey: 'ratatui-markdown.description',
    techStack: ['Rust', 'ratatui', 'Tree-sitter'],
    status: 'active',
    repo: 'celestia-island/ratatui-markdown',
    color: '#0ea5e9',
    icon: 'i-lucide-scroll-text',
  },
  {
    id: 'yuuka',
    name: 'Yuuka',
    nameKey: 'yuuka.name',
    shortLabel: 'Nested Type Generator',
    shortLabelKey: 'yuuka.shortLabel',
    tagline: 'Define deeply nested types in one sweep',
    taglineKey: 'yuuka.tagline',
    description: 'A proc-macro library that generates complex, deeply nested structs and enums from a compact DSL. Inline types are automatically flattened, derived, and wired up with serde — write one macro invocation, get an entire type hierarchy.',
    descriptionKey: 'yuuka.description',
    techStack: ['Rust', 'proc-macro', 'Serde'],
    status: 'active',
    repo: 'celestia-island/yuuka',
    color: '#a78bfa',
    icon: 'i-lucide-layers',
  },
  {
    id: 'ichika',
    name: 'Ichika',
    nameKey: 'ichika.name',
    shortLabel: 'Pipeline Threading Library',
    shortLabelKey: 'ichika.shortLabel',
    tagline: 'Declarative thread-pool pipelines via macro',
    taglineKey: 'ichika.tagline',
    description: 'Declaratively define multi-stage processing pipelines from closures. The pipe! macro generates all thread wiring and channel plumbing automatically — supporting mixed sync/async steps, branching, retry policies, and graceful shutdown.',
    descriptionKey: 'ichika.description',
    techStack: ['Rust', 'proc-macro', 'Flume', 'Tokio'],
    status: 'active',
    repo: 'celestia-island/ichika',
    color: '#14b8a6',
    icon: 'i-lucide-workflow',
  },
  {
    id: 'hifumi',
    name: 'Hifumi',
    nameKey: 'hifumi.name',
    shortLabel: 'Data Migration Library',
    shortLabelKey: 'hifumi.shortLabel',
    tagline: 'Version your structs, migrate your data',
    taglineKey: 'hifumi.tagline',
    description: 'A serialization library for migrating data between struct versions. Annotate your types with version attributes and migration rules — Hifumi auto-generates all older-version structs and From impls, plus a CLI to diff structs across git history.',
    descriptionKey: 'hifumi.description',
    techStack: ['Rust', 'proc-macro', 'Serde', 'Git'],
    status: 'active',
    repo: 'celestia-island/hifumi',
    color: '#d946ef',
    icon: 'i-lucide-git-compare',
  },
  {
    id: 'noa',
    name: 'Noa',
    nameKey: 'noa.name',
    shortLabel: 'Rust Doc Generator',
    shortLabelKey: 'noa.shortLabel',
    tagline: 'AI-powered Rust documentation from source',
    taglineKey: 'noa.tagline',
    description: 'A document generator for Rust crates that produces Markdown, static HTML sites, and AI-powered multi-language translations — all from your source code and doc comments.',
    descriptionKey: 'noa.description',
    techStack: ['Rust', 'Clap', 'Serde'],
    status: 'preview',
    repo: 'celestia-island/noa',
    color: '#fb923c',
    icon: 'i-lucide-book-open',
  },
]
