name: Format

on:
  pull_request:
    paths:
      - '.github/workflows/fmt.yml'
      - 'docs/**'
      - '**/*.md'
      - 'justfile'
      - 'celestia-devtools.just'
  push:
    branches: [main]

jobs:
  format:
    name: Markdown format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: extractions/setup-just@v2
        with:
          version: "1.40.0"
      - run: just ensure
      - run: just fmt-check
